version: '3.8'

services:
  # Fitness Builder API
  fitness-builder:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT:-5432}
      - PG_DBNAME=${PG_DBNAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_API_BACKUP_KEY=${GEMINI_API_BACKUP_KEY}
      - AI_PROVIDER=${AI_PROVIDER:-gemini}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - fitness_storage:/app/storage
      - fitness_temp:/app/storage/temp
      - fitness_compiled:/app/storage/compiled_workouts
    restart: unless-stopped
    networks:
      - fitness_network

volumes:
  fitness_storage:
  fitness_temp:

networks:
  fitness_network:
    driver: bridge
